# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eca598c294d6d921aaaa67b81c4d772c8584d1961921b7f3c6476ee28e557f32b15dc02cfd8fdaf55d55209cb4e3dbfad114cf6e8cb771e83572a579759764f

test:
  secret_key_base: 54669b900fc1e17de9b72fcba1f9829eb1d1752491564f4485db60cd9829caeda7aaa461dd5c2511ee0b6113c6b3ce8e86ed2e23f6bfb813cb4c6d4ea7d8540e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
